name: CI

on:
  push:
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true

      - name: Install dependencies
        run: |
          go mod download
          go run honnef.co/go/tools/cmd/staticcheck@latest
          go run github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run gosec
        run: gosec ./...

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v
